name: main

on:
  push:
    branches: [master, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.5.0
    with:
      env: '["py39", "py310", "py311"]'
      os: ubuntu-latest
